version: "3.9"  # optional since v1.27.0
services:
  node1:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: node1
    image: node1
    environment:
      - NAME=node1
      - NODES_TO_CONTROL="node1 node2 node3 node4"
      - CONTROL_SYSTEM_NODES="node1 node2 node3 node4"
    ports:
      - "8080:8080"
  node2:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: node2
    image: node2
    environment:
      - NAME=node2
      - NODES_TO_CONTROL="node1 node2 node3 node4"
      - CONTROL_SYSTEM_NODES="node1 node2 node3 node4"
  node3:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: node3
    image: node3
    environment:
      - NAME=node3
      - NODES_TO_CONTROL="node1 node2 node3 node4"
      - CONTROL_SYSTEM_NODES="node1 node2 node3 node4"
  node4:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: node4
    image: node4
    environment:
      - NAME=node4
      - NODES_TO_CONTROL="node1 node2 node3 node4"
      - CONTROL_SYSTEM_NODES="node1 node2 node3 node4"